### ISSUE TITLE
更新到0.7后，app显示未安装模块

### ISSUE THREAD

**Issue by liyiecho** [taamarin/box_for_magisk#10]
模块更新到0.7后，app显示未安装模块
![Screenshot_2023-04-09-15-04-14-564_xyz.chz.bfm.jpg](https://user-images.githubusercontent.com/5213722/230759674-bf8381e9-2ae2-4ba1-b794-e565ea519189.jpg)

![Screenshot_2023-04-09-15-05-35-852_w.qonczii.faug.as.png](https://user-images.githubusercontent.com/5213722/230759683-61ce5468-a77e-4311-ae9d-8989e7978158.png)

还是说以后不需要app了

**Comment by JeelsBoobz** [comment]
Update app https://t.me/taamarin/170010

**Comment by liyiecho** [comment]
> Update app https://t.me/taamarin/170010

Thanks

**Comment by heqirong** [comment]
> Update app https://t.me/taamarin/170010

app没有bfm manager
