### ISSUE TITLE
开启IPV6后DNS出现泄露问题

### ISSUE THREAD

**Issue by Nep-Timeline** [taamarin/box_for_magisk#107]
Clash Meta配置: https://github.com/Nep-Timeline/Clash-Rule-Set/blob/main/Configs/ClashMeta_Linux.yaml

**Comment by flyflas** [comment]
ipv6有bug，可能出现回环。建议只使用ipv4

**Comment by Nep-Timeline** [comment]
> ipv6有bug，可能出现回环。建议只使用ipv4

回环只在TPROXY出现, Tun模式不会

**Comment by Nep-Timeline** [comment]
似乎只有丢弃IPV6 UDP 53端口的所有请求才能解决
