### ISSUE TITLE
三星设备启用模块后无法通话

### ISSUE THREAD

**Issue by ZerotwoYu** [taamarin/box_for_magisk#130]
三星Galaxy S22 oneui6.1
上网和透明代理一切正常，无法接打电话和收发短信，尝试过更换内核。

**Comment by chthlzy** [comment]
三星s23u oneui6.1
 同样 使用一段时间后无法接打电话和接受发短信，关闭模块后开关飞行模式可正常，再次打开模块一段时间后又出现这个bug

**Comment by Piggy-Cat-bit** [comment]
你可以将以下包名添加到黑名单
  - com.samsung.android.messaging
    - com.samsung.android.app.telephonyui
    - com.samsung.android.smartcallprovider
    - com.samsung.android.intellivoiceservice
    - com.android.settings
    - com.sec.imsservice
   我这边已经没问题了，可以正常收到通话

**Comment by ZerotwoYu** [comment]
> 你可以将以下包名添加到黑名单
> 
> * com.samsung.android.messaging
>   
>   * com.samsung.android.app.telephonyui
>   * com.samsung.android.smartcallprovider
>   * com.samsung.android.intellivoiceservice
>   * com.android.settings
>   * com.sec.imsservice
>     我这边已经没问题了，可以正常收到通话

非常感谢，已经解决了

**Comment by Piggy-Cat-bit** [comment]
如果你是双卡用户，最好多添加以下这些包名，比上一版多增加了几个，最近这几天发现的，不然你会漏接另一张卡的电话，接收不到另一张卡的短信
 - com.samsung.android.messaging
  - com.samsung.android.app.telephonyui
  - com.samsung.android.dialer
  - com.samsung.android.incallui
  - com.samsung.android.smartcallprovider
  - com.samsung.android.intellivoiceservice
  - com.android.settings
  - com.qti.qcc
  - com.sec.epdg
  - com.sec.imsservice

**Comment by AXEVO** [comment]
如果用的是tun，参考这里https://github.com/CHIZI-0618/box4magisk/issues/38  修改下exclude-uid可能也行

**Comment by AXEVO** [comment]
> > 你可以将以下包名添加到黑名单
> > 
> > * com.samsung.android.messaging
> >   
> >   * com.samsung.android.app.telephonyui
> >   * com.samsung.android.smartcallprovider
> >   * com.samsung.android.intellivoiceservice
> >   * com.android.settings
> >   * com.sec.imsservice
> >     我这边已经没问题了，可以正常收到通话
> 
> 非常感谢，已经解决了

楼主放不方便发一下配置文件？我也遇到了这个问题，但是添加这几个包名依旧不行，系统也是oneui6.1.1，除了这些我还添加了这里说的，都不行

https://github.com/MoGuangYu/Surfing/issues/63

**Comment by ZerotwoYu** [comment]
> > > 你可以将以下包名添加到黑名单
> > > 
> > > * com.samsung.android.messaging
> > >   
> > >   * com.samsung.android.app.telephonyui
> > >   * com.samsung.android.smartcallprovider
> > >   * com.samsung.android.intellivoiceservice
> > >   * com.android.settings
> > >   * com.sec.imsservice
> > >     我这边已经没问题了，可以正常收到通话
> > 
> > 
> > 非常感谢，已经解决了
> 
> 楼主放不方便发一下配置文件？我也遇到了这个问题，但是添加这几个包名依旧不行，系统也是oneui6.1.1，除了这些我还添加了这里说的，都不行
> 
> [MoGuangYu/Surfing#63](https://github.com/MoGuangYu/Surfing/issues/63)

我已经不用这个模块了，我看了一下就是加在exclude-package字段下，和你的配置一样

**Comment by AXEVO** [comment]
> > > > 你可以将以下包名添加到黑名单
> > > > 
> > > > * com.samsung.android.messaging
> > > >   
> > > >   * com.samsung.android.app.telephonyui
> > > >   * com.samsung.android.smartcallprovider
> > > >   * com.samsung.android.intellivoiceservice
> > > >   * com.android.settings
> > > >   * com.sec.imsservice
> > > >     我这边已经没问题了，可以正常收到通话
> > > 
> > > 
> > > 非常感谢，已经解决了
> > 
> > 
> > 楼主放不方便发一下配置文件？我也遇到了这个问题，但是添加这几个包名依旧不行，系统也是oneui6.1.1，除了这些我还添加了这里说的，都不行
> > [MoGuangYu/Surfing#63](https://github.com/MoGuangYu/Surfing/issues/63)
> 
> 我已经不用这个模块了，我看了一下就是加在exclude-package字段下，和你的配置一样

那 楼主可否告知下现在还在用什么模块吗？还有掉volte的问题吗？

**Comment by ZerotwoYu** [comment]
> > > > > 你可以将以下包名添加到黑名单
> > > > > 
> > > > > * com.samsung.android.messaging
> > > > >   
> > > > >   * com.samsung.android.app.telephonyui
> > > > >   * com.samsung.android.smartcallprovider
> > > > >   * com.samsung.android.intellivoiceservice
> > > > >   * com.android.settings
> > > > >   * com.sec.imsservice
> > > > >     我这边已经没问题了，可以正常收到通话
> > > > 
> > > > 
> > > > 非常感谢，已经解决了
> > > 
> > > 
> > > 楼主放不方便发一下配置文件？我也遇到了这个问题，但是添加这几个包名依旧不行，系统也是oneui6.1.1，除了这些我还添加了这里说的，都不行
> > > [MoGuangYu/Surfing#63](https://github.com/MoGuangYu/Surfing/issues/63)
> > 
> > 
> > 我已经不用这个模块了，我看了一下就是加在exclude-package字段下，和你的配置一样
> 
> 那 楼主可否告知下现在还在用什么模块吗？还有掉volte的问题吗？

现在直接用软路由+旁路由做透明代理了，局域网内的设备没有安装模块或应用

**Comment by AXEVO** [comment]
> > > > 你可以将以下包名添加到黑名单
> > > > 
> > > > * com.samsung.android.messaging
> > > >   
> > > >   * com.samsung.android.app.telephonyui
> > > >   * com.samsung.android.smartcallprovider
> > > >   * com.samsung.android.intellivoiceservice
> > > >   * com.android.settings
> > > >   * com.sec.imsservice
> > > >     我这边已经没问题了，可以正常收到通话
> > > 
> > > 
> > > 非常感谢，已经解决了
> > 
> > 
> > 楼主放不方便发一下配置文件？我也遇到了这个问题，但是添加这几个包名依旧不行，系统也是oneui6.1.1，除了这些我还添加了这里说的，都不行
> > [MoGuangYu/Surfing#63](https://github.com/MoGuangYu/Surfing/issues/63)
> 
> 我已经不用这个模块了，我看了一下就是加在exclude-package字段下，和你的配置一样

楼主还有没有印象当时你有没有在配置里开启IPv6了，我添加了谢谢不好使但是开启IPv6就能行了，我想确定下是不是这个的问题

**Comment by ZerotwoYu** [comment]
> > > > > 你可以将以下包名添加到黑名单
> > > > > 
> > > > > * com.samsung.android.messaging
> > > > >   
> > > > >   * com.samsung.android.app.telephonyui
> > > > >   * com.samsung.android.smartcallprovider
> > > > >   * com.samsung.android.intellivoiceservice
> > > > >   * com.android.settings
> > > > >   * com.sec.imsservice
> > > > >     我这边已经没问题了，可以正常收到通话
> > > > 
> > > > 
> > > > 非常感谢，已经解决了
> > > 
> > > 
> > > 楼主放不方便发一下配置文件？我也遇到了这个问题，但是添加这几个包名依旧不行，系统也是oneui6.1.1，除了这些我还添加了这里说的，都不行
> > > [MoGuangYu/Surfing#63](https://github.com/MoGuangYu/Surfing/issues/63)
> > 
> > 
> > 我已经不用这个模块了，我看了一下就是加在exclude-package字段下，和你的配置一样
> 
> 楼主还有没有印象当时你有没有在配置里开启IPv6了，我添加了谢谢不好使但是开启IPv6就能行了，我想确定下是不是这个的问题

开了的
