### ISSUE TITLE
安卓11 singbox tun 日志提示 start service: initialize inbound/tun[0]: configure tun interface: permission denied

### ISSUE THREAD

**Issue by ossfile** [taamarin/box_for_magisk#151]
求指导应该怎么解决？
命令行 su -c /data/adb/box/scripts/box.service 没有报错输出，查看singbox日志提示
[31mFATAL[0m[0008] start service: initialize inbound/tun[0]: configure tun interface: permission denied

目前尝试过修改settings.ini中的box_user_group="root:net_admin"为box_user_group="root:root"，但无效被自动修改回原设置，使用官方tun设置或者脚本内的tun设置运行无报错，但是查看singbox日志都是提示权限不足，求大佬指导，谢谢。

**Comment by TrioTea** [comment]
看一下你的singbox的tun配置呢？

**Comment by ossfile** [comment]
"inbounds": [
    {
    "type": "tun",
    "tag": "tun-in",
    "interface_name": "tun0",
    "address": [
      "172.18.0.1/30"    
    ],
    "mtu": 9000,
    "auto_route": true,
    "strict_route": true,
    "stack": "system"
    }
  ],

您好，tun配置如上，使用的是singbox1.10.1版本，尝试过删掉inbounds，使用脚本内置的tun配置，但同样服务运行界面无异常，重启提示服务已关闭，查看singbox日志提示start service: initialize inbound/tun[0]: configure tun interface: permission denied，似乎是没有权限，求指导或给点思路，晚上我再测试看看哪方面出现问题。

**Comment by TrioTea** [comment]
> "inbounds": [ { "type": "tun", "tag": "tun-in", "interface_name": "tun0", "address": [ "172.18.0.1/30" ], "mtu": 9000, "auto_route": true, "strict_route": true, "stack": "system" } ],
> 
> 您好，tun配置如上，使用的是singbox1.10.1版本，尝试过删掉inbounds，使用脚本内置的tun配置，但同样服务运行界面无异常，使用su -c /data/adb/box/scripts/box.service restart 重启提示之前的服务已关闭后正常启用服务，但查看singbox日志提示start service: initialize inbound/tun[0]: configure tun interface: permission denied，似乎是没有权限，求指导或给点思路，晚上我再测试看看哪方面出现问题。

你好，我之前一直是使用的mihomo内核，最近几天才转为使用singbox，目前最新版是正常的，所以我只能尝试帮助你解决一下，但是谈不上指导🙂
我没修改过box_user_group以及其他的一些配置，我在过去的使用中暂时也没有遇到类似的问题，或许你可以尝试删除模块重新载入，这里附上我使用的入站配置，看看会不会有帮助

```json
"inbounds": [
    {
      "tag": "tun",
      "type": "tun",
      "interface_name": "singbox",
      "address": [
        "172.19.0.0/30"
      ],
      "auto_route": true,
      "strict_route": true,
      "sniff": true,
      "endpoint_independent_nat": false,
      "stack": "system",
      "platform": {
        "http_proxy": {
          "enabled": true,
          "server": "127.0.0.1",
          "server_port": 2080
        }
      }
    },
    {
      "tag": "mixed",
      "type": "mixed",
      "listen": "127.0.0.1",
      "listen_port": 2080,
      "sniff": true,
      "users": []
    }
  ]
```

**Comment by ossfile** [comment]
非常感谢，配置未修改，重装后已正常运行。
