### ISSUE TITLE
用不了 google 系软件， Google play ，voice， 和 youtube

### ISSUE THREAD

**Issue by gitduk** [taamarin/box_for_magisk#160]
youtube 需要用 google 账户登录，所以也加载不了

但是在浏览器里面可以正常访问 youtube ，google play 和 voice

**Comment by joseph-lincc** [comment]
刷入telegram频道发布的BFM v1.7.5(d3b7d6e)(7236198)后，出现相同的问题。

**Comment by joseph-lincc** [comment]
我是刷了最新的v1.7.5(d3b7d6e)(7236198)，出现了同样的问题。
经检查发现package.list.ini里默认添加了google的应用，删除后恢复正常。

**Comment by gitduk** [comment]
> 我是刷了最新的v1.7.5([d3b7d6e](https://github.com/taamarin/box_for_magisk/commit/d3b7d6ef9c892919734d144e66cf9eda0ffe27fe))([7236198](https://github.com/taamarin/box_for_magisk/commit/72361987a8a18605327df56c2d2a546e0758f884))，出现了同样的问题。 经检查发现package.list.ini里默认添加了google的应用，删除后恢复正常。

v1.7.5 打包文件里面没有package.list.ini 文件吧

**Comment by gitduk** [comment]
> > > 我是刷了最新的v1.7.5([d3b7d6e](https://github.com/taamarin/box_for_magisk/commit/d3b7d6ef9c892919734d144e66cf9eda0ffe27fe))([7236198](https://github.com/taamarin/box_for_magisk/commit/72361987a8a18605327df56c2d2a546e0758f884))，出现了同样的问题。 经检查发现package.list.ini里默认添加了google的应用，删除后恢复正常。
> > 
> > 
> > v1.7.5 打包文件里面没有package.list.ini 文件吧
> 
> 哦，我刷的是telegram里最新发布的版本，有配置的改动。v1.7.5目前的正式版里是没有，倒是也没出现这个问题。

老哥用的是 clash 内核吗，我用的是 sing-box 有这个问题，clash 没有试过

**Comment by joseph-lincc** [comment]
> > > > 我是刷了最新的v1.7.5([d3b7d6e](https://github.com/taamarin/box_for_magisk/commit/d3b7d6ef9c892919734d144e66cf9eda0ffe27fe))([7236198](https://github.com/taamarin/box_for_magisk/commit/72361987a8a18605327df56c2d2a546e0758f884))，出现了同样的问题。 经检查发现package.list.ini里默认添加了google的应用，删除后恢复正常。
> > > 
> > > 
> > > v1.7.5 打包文件里面没有package.list.ini 文件吧
> > 
> > 
> > 哦，我刷的是telegram里最新发布的版本，有配置的改动。v1.7.5目前的正式版里是没有，倒是也没出现这个问题。
> 
> 老哥用的是 clash 内核吗，我用的是 sing-box 有这个问题，clash 没有试过

对，clash没出现什么问题就一直用了。

**Comment by TrioTea** [comment]
singbox没有遇到这个问题

**Comment by gitduk** [comment]
> singbox没有遇到这个问题

难道是我的 singbox 配置文件的问题？
老哥方便分享一下你的配置文件模板吗

**Comment by TrioTea** [comment]
你是使用的tproxy吗？你参考一下我的配置文件，我暂时没遇到使用的问题
https://github.com/TrioTea/MyProfileHub/blob/master/sing-box/singbox-realip.json

**Comment by TrioTea** [comment]
我目前使用的box_for_magisk是最新版，singbox使用的1.10.3

**Comment by gitduk** [comment]
> 你是使用的tproxy吗？你参考一下我的配置文件，我暂时没遇到使用的问题 https://github.com/TrioTea/MyProfileHub/blob/master/sing-box/singbox-realip.json

对，我用的 tproxy
非常感谢，我试试你的配置模板，看看怎么个事

**Comment by TrioTea** [comment]
> > 你是使用的tproxy吗？你参考一下我的配置文件，我暂时没遇到使用的问题 https://github.com/TrioTea/MyProfileHub/blob/master/sing-box/singbox-realip.json
> 
> 对，我用的 tproxy 非常感谢，我试试你的配置模板，看看怎么个事

哈哈，试一试，我也是缝合了一些大佬的文件，目前稳定了一段时间

**Comment by gitduk** [comment]
> > > 你是使用的tproxy吗？你参考一下我的配置文件，我暂时没遇到使用的问题 https://github.com/TrioTea/MyProfileHub/blob/master/sing-box/singbox-realip.json
> > 
> > 
> > 对，我用的 tproxy 非常感谢，我试试你的配置模板，看看怎么个事
> 
> 哈哈，试一试，我也是缝合了一些大佬的文件，目前稳定了一段时间

还是不行，用这个配置模板，singbox 正常运行，但是 www.google.com 都没法访问了

**Comment by TrioTea** [comment]
好不科学

**Comment by lacanzizek** [comment]
> 你是使用的tproxy吗？你参考一下我的配置文件，我暂时没遇到使用的问题 https://github.com/TrioTea/MyProfileHub/blob/master/sing-box/singbox-realip.json

请问下机场订阅链接是填在那个部分

**Comment by TrioTea** [comment]
> > 你是使用的tproxy吗？你参考一下我的配置文件，我暂时没遇到使用的问题 https://github.com/TrioTea/MyProfileHub/blob/master/sing-box/singbox-realip.json
> 
> 请问下机场订阅链接是填在那个部分

要自己进行合并，不支持直接填写机场链接
