### ISSUE TITLE
[BUG] The ipv6 option in the 0.8 version settings will globally replace the ipv6 option in the clash configuration

### ISSUE THREAD

**Issue by haiOG** [taamarin/box_for_magisk#17]
Setting ipv6:true in the setting.ini will cause the ipv6:ip option of the wireguard node to be forcibly reset to true.
Then it will throw an error that ipv6 cannot be a string.
like this
- name: "WG"
  type: wireguard
  server: xxx
  port: xxx
  ip: xxx
  ipv6: true
  private-key: xxx
  public-key: xxx
  mtu: 1280
  udp: true

**Comment by taamarin** [comment]
> Setting ipv6:true in the setting.ini will cause the ipv6:ip option of the wireguard node to be forcibly reset to true. Then it will throw an error that ipv6 cannot be a string. like this
> 
> * name: "WG"
>   type: wireguard
>   server: xxx
>   port: xxx
>   ip: xxx
>   ipv6: true
>   private-key: xxx
>   public-key: xxx
>   mtu: 1280
>   udp: true

Delete this line
https://github.com/taamarin/box_for_magisk/blob/3c64fad0c5a7589aca77215d8125ddaf54e69b68/box/scripts/box.service#L162

**Comment by haiOG** [comment]
> 

thanks!

**Comment by haiOG** [comment]
> 

thanks!

> > 
> 
> thanks!

**Comment by haiOG** [comment]
> > Setting ipv6:true in the setting.ini will cause the ipv6:ip option of the wireguard node to be forcibly reset to true. Then it will throw an error that ipv6 cannot be a string. like this
> > 
> > * name: "WG"
> >   type: wireguard
> >   server: xxx
> >   port: xxx
> >   ip: xxx
> >   ipv6: true
> >   private-key: xxx
> >   public-key: xxx
> >   mtu: 1280
> >   udp: true
> 
> Delete this line
> 
> https://github.com/taamarin/box_for_magisk/blob/3c64fad0c5a7589aca77215d8125ddaf54e69b68/box/scripts/box.service#L162

thanks!
