### ISSUE TITLE
安装v0.4后手机无限重启

### ISSUE THREAD

**Issue by liyiecho** [taamarin/box_for_magisk#3]
小米10 MIUI14(安卓13）
每次自动重启都会进入小米官方rec，选择开机，进入桌面未解锁屏幕之前都是正常的，解锁进入桌面后过几秒后就会再次进入小米官方rec。通过那短暂的几秒进入magisk关闭本模块，重启后就恢复正常了。

**Comment by taamarin** [comment]
检查位于 /data/adb/box/run 文件夹中的 service.log 和 runs.log。

**Comment by liyiecho** [comment]
看了一下错误大概就是在service.log里面的，

```
W0305 01:05:06.789774   12670 cpuid.go:251] cpuid HWCap not initialized: %!w(*errors.errorString=&{readHwCap only supported on linux, not android})
mv: can't rename '/data/adb/box/run/sing-box.log': No such file or directory
mv: can't rename '/data/adb/box/run/xray.log': No such file or directory
mv: can't rename '/data/adb/box/run/v2fly.log': No such file or directory
ifconfig: : error fetching interface information: Device not found

Parse error: bad token
    <stdin>:1


Parse error: bad token
    <stdin>:1


Parse error: bad token
    <stdin>:1
```

[service.log](https://github.com/taamarin/box_for_magisk/files/10890725/service.log)
[runs.log](https://github.com/taamarin/box_for_magisk/files/10890727/runs.log)

**Comment by taamarin** [comment]
请在此行前加上#或直接删除此行。

https://github.com/taamarin/box_for_magisk/blob/master/scripts/src/box.service#L426
https://github.com/taamarin/box_for_magisk/blob/master/scripts/src/box.service#L445

**Comment by liyiecho** [comment]
注释了之后，service.log 和 runs.log没看到什么报错，但仍然无限重启

**Comment by liyiecho** [comment]
不知道是否跟magsik版本有关系，现在用的是magsik 25.2的

**Comment by taamarin** [comment]
> 不知道是否跟magsik版本有关系，现在用的是magsik 25.2的

我也使用Magisk 25.x，但没有使用MIUI 14。

请将 https://github.com/taamarin/box_for_magisk/blob/master/scripts/settings.ini#L3 删除，并更换为 Flash Module BusyBox For android NDK。

**Comment by liyiecho** [comment]
> > 不知道是否跟magsik版本有关系，现在用的是magsik 25.2的
> 
> 我也使用Magisk 25.x，但没有使用MIUI 14。
> 
> 请将 https://github.com/taamarin/box_for_magisk/blob/master/scripts/settings.ini#L3 删除，并更换为 Flash Module BusyBox For android NDK。

已按要求操作安装busybox，但依然自动重启。

**Comment by liyiecho** [comment]
@razilong 可我没装这个模块，而且把其他模块都禁用只开启box_for_magisk模块，也一样无限重启

**Comment by liyiecho** [comment]
@taamarin 用log catcher模块抓了一下启动log，麻烦你看一下

[boot-2023-03-11-08-45-54.zip](https://github.com/taamarin/box_for_magisk/files/10947211/boot-2023-03-11-08-45-54.zip)

**Comment by whao123yahoo** [comment]
run.log里面提示没有clash，让我下载放到/data/adb/box/bin/clash目录里面，但是找不到安卓版本的。。。下了个linux-arm64的放进去了，还是一样的提示。求指导🌝

**Comment by taamarin** [comment]
> runs.log里面提示没有clash，让我下载放到/data/adb/box/bin/clash目录里面，但是找不到安卓版本的。。。下了个linux-arm64的放进去了，还是一样的提示。求指导🌝

![Screenshot_20230315-220448](https://user-images.githubusercontent.com/71506581/225352343-b3c40428-322b-4e84-8e04-283df015ae68.png)

**Comment by whao123yahoo** [comment]
> > runs.log里面提示没有clash，让我下载放到/data/adb/box/bin/clash目录里面，但是找不到安卓版本的。。。下了个linux-arm64的放进去了，还是一样的提示。求指导🌝
> 
> ![Screenshot_20230315-220448](https://user-images.githubusercontent.com/71506581/225352343-b3c40428-322b-4e84-8e04-283df015ae68.png)
> 

3q。原来是我会错意了，又建了个子目录放进去的，难怪不行。这Linux的东西，只要是不带后缀名的我还都以为是个目录呢，没想到就已经是文件了😂

**Comment by whao123yahoo** [comment]
后台进不去，不知道是我配置是不是有问题？我看config.yaml文件里面已经正确获取到我订阅的各个服务器的信息了，但是127.0.0.1:9090进去只提示个Hello😂，而且一旦开启服务就全局没有网络连接了

**Comment by taamarin** [comment]
> 后台进不去，不知道是我配置是不是有问题？我看config.yaml文件里面已经正确获取到我订阅的各个服务器的信息了，但是127.0.0.1:9090进去只提示个Hello😂，而且一旦开启服务就全局没有网络连接了

http://127.0.0.1:9090/ui

**Comment by whao123yahoo** [comment]
> > 后台进不去，不知道是我配置是不是有问题？我看config.yaml文件里面已经正确获取到我订阅的各个服务器的信息了，但是127.0.0.1:9090进去只提示个Hello😂，而且一旦开启服务就全局没有网络连接了
> 
> http://127.0.0.1:9090/ui

页面提示404 not found。。。不晓得怎么回事，看视频挺简单，而且我照着做的时候，都没有报错，结果启动服务了，各种问题都会遇到😂

**Comment by liyiecho** [comment]
MIUI14 V14.0.23.3.13.DEV
 box_for_magisk-v0.4.2 
bfm_manager-v2.0.1
现在又莫名其妙得好了，不会无限重启了

**Comment by liyiecho** [comment]
更新v0.5之后又无限重启了，但是发现不创建resolve.conf后就能正常开机了。目前没有写入resolve.conf文件，暂时没发现有什么影响。
还有就是，有时候下载内核跟geox不完整，会缺失文件。

**Comment by taamarin** [comment]
> 更新v0.5之后又无限重启了，但是发现不创建resolve.conf后就能正常开机了。目前没有写入resolve.conf文件，暂时没发现有什么影响。 还有就是，有时候下载内核跟geox不完整，会缺失文件。

使用 su -c /data/adb/box/scripts/box.tool subgeo 命令下载 GEO，使用 su -c /data/adb/box/scripts/box.tool upcore 命令下载内核。

**Comment by liyiecho** [comment]
@taamarin 另外请问不用resolve.conf这个文件会有什么影响吗

**Comment by taamarin** [comment]
> @taamarin 另外请问不用resolve.conf这个文件会有什么影响吗

![Screenshot_20230320-130200](https://user-images.githubusercontent.com/71506581/226260072-d8462dac-0d1a-4514-bbf4-9d970ed97933.png)

可能在一些设备上会遇到这个问题。
https://stackoverflow.com/questions/25785568/go-etc-resolv-conf-missing-in-android
https://github.com/Asterisk4Magisk/Xray4Magisk/issues/12
