### ISSUE TITLE
发现个问题，似乎不能将订阅地址里的分流规则自动添加到 config.yaml 里？

### ISSUE THREAD

**Issue by goxofy** [taamarin/box_for_magisk#42]

**Comment by goxofy** [comment]
> https://github.com/taamarin/box_for_magisk/blob/632d16e312521d96e963a35c479f9e6a6dc53d90/box/settings.ini#L79-L81
> 
> set "true"

谢谢，试了一下这个似乎是直接将订阅文件替换config.yaml，如果能像nodes一样，仅整合rules信息就好了

**Comment by tw4452852** [comment]
With #44 , you could replace rules in `config.yaml` with the ones in subscription.

**Comment by goxofy** [comment]
yes，i have did this

**Comment by taamarin** [comment]
> With #44 , you could replace rules in `config.yaml` with the ones in subscription.

Looks like the error occurs if the subscription has a "rule-provider:"
