### ISSUE TITLE
sing-box开启后没有网络

### ISSUE THREAD

**Issue by yaohuow** [taamarin/box_for_magisk#46]
sing-box的模式可以在神秘和E5 86 95的box4上正常使用，但是在box_for_root上却无法使用，替换了内核也不行
![Screenshot_2023-08-24-19-31-23-594_bin mt plus-edit](https://github.com/taamarin/box_for_magisk/assets/54373869/6d3f9366-2137-4a3e-a00c-0ce2d5d0b0a3)
![Screenshot_2023-08-24-19-30-53-924_bin mt plus-edit](https://github.com/taamarin/box_for_magisk/assets/54373869/7909a346-9acd-4747-9c7d-72818314ae42)

**Comment by 51rxjh** [comment]
面板可以正常打开，但是无法测网，节点不亮

**Comment by 51rxjh** [comment]
已经解决

**Comment by 51rxjh** [comment]
已经解决
