### ISSUE TITLE
Dashboard 打开是404

### ISSUE THREAD

**Issue by laopo001** [taamarin/box_for_magisk#5]
Dashboard 打开是404，小米手机11pro ，miui14

**Comment by taamarin** [comment]
> Dashboard 打开是404，小米手机11pro ，miui14

```yaml
external-ui: /data/adb/box/yacd
```

创建文件夹 /data/adb/box/yacd，在 /yacd 文件夹深度中添加 [yacd](https://github.com/MetaCubeX/Yacd-meta/archive/refs/heads/gh-pages.zip) 文件。

**Comment by laopo001** [comment]
谢谢，昨天看了下代码，确实缺这个属性。但是我在配置中加了，clash verge桌面的代理软件，也会读取external-ui，导致clash verge面板不能用，这个最好在没配置这个属性的时候，给个默认值external-ui: ./dashboard/dist

**Comment by taamarin** [comment]
> 谢谢，昨天看了下代码，确实缺这个属性。但是我在配置中加了，clash verge桌面的代理软件，也会读取external-ui，导致clash verge面板不能用，这个最好在没配置这个属性的时候，给个默认值external-ui: ./dashboard/dist

很好的想法 😃
