### ISSUE TITLE
[功能建议]支持自定义ua/适配clash订阅链

### ISSUE THREAD

**Issue by ShanshanHY** [taamarin/box_for_magisk#51]
目前我所用的v2board面板机场会根据请求订阅时的ua来分发不同的配置，比如ua中含有clash会直接下发clash配置文件，没有匹配到ua则默认下发base64编码的ss订阅链
我知道可以直接通过直接修改box.tool内的ua，但这个文件好像会被模块的更新覆盖，所以还是希望能在settings.ini中直接设置，或者针对clash的订阅链直接设置ua为clash

**Comment by taamarin** [comment]
去做就对了。
冲突部分将得到纠正。

**Comment by ShanshanHY** [comment]
Thanks for reply.
I just found that the modules update with a full backup  for old folder, and all files will be copy from new version. Is that's meaning I have to copy my config from old backup folder to new folder？

**Comment by taamarin** [comment]
> Thanks for reply. I just found that the modules update with a full backup for old folder, and all files will be copy from new version. Is that's meaning I have to copy my config from old backup folder to new folder？

No need, the module will automatically back up your configuration in the folder named box.XXXX and restore it automatically.

**Comment by ShanshanHY** [comment]
tks, i got it
