### ISSUE TITLE
box.tool更新的问题，

### ISSUE THREAD

**Issue by yaohuow** [taamarin/box_for_magisk#57]
在MIUI14上使用box.tool更新时，无法更新下载对应的资源，能否更改为使用curl进行下载相关资源？

**Comment by yaohuow** [comment]
![Screenshot_2023-10-27-13-41-23-353_bin mt plus-edit](https://github.com/taamarin/box_for_magisk/assets/54373869/5a0f2039-ed35-4ae1-ae4c-71ec4cc19f3a)

**Comment by taamarin** [comment]
如何修复 wget 错误。
https://t.me/taamarin/223958/266502

**Comment by yaohuow** [comment]
> 如何修复 wget 错误。 https://t.me/taamarin/223958/266502

好的，问题已解决，谢谢您的帮助！

**Comment by taamarin** [comment]
> > > 如何修复 wget 错误。 https://t.me/taamarin/223958/266502
> > 
> > 
> > 好的，问题已解决，谢谢您的帮助！
> 
> 这个怎么搞啊，群消息删除了，我找不到回复

Update 1.4.2
