### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [taamarin/box_for_magisk#8]
First thanks for making your module available here! Can you please clarify what license applies to it?

**Comment by taamarin** [comment]
> First thanks for making your module available here! Can you please clarify what license applies to it?

Implementing GNU GPL v3.0

**Comment by IzzySoft** [comment]
Great, thanks!

**Comment by IzzySoft** [comment]
OK, added it to [my repo](https://apt.izzysoft.de/magisk) now. Just a pointer: your latest `module.prop` is "broken", as `name` is empty :wink:

**Comment by taamarin** [comment]
> OK, added it to [my repo](https://apt.izzysoft.de/magisk) now. Just a pointer: your latest `module.prop` is "broken", as `name` is empty 😉

Will be automatically written after reboot

https://github.com/taamarin/box_for_magisk/blob/a01d185099706a8acd516040ac3444aa9dcd7d61/customize.sh#L114-L118

**Comment by IzzySoft** [comment]
"After reboot" doesn't help much when that property is used for listing in the catalog :rofl: See the link above. I've just replaced the `module.prop` with one that has the name set, else the name would be gone each time the catalog is updated (which currently is multiple times a day, as the catalog is still WIP and modules are added daily). If it's updated after each boot anyway, maybe a "generic name" could be set by default, e.g. "Box for Magisk/KernelSU"?

**Comment by taamarin** [comment]
> 

"Hahaha, it seems like I have to try on multiple devices, yes it now supports Magisk and KernelSU."

**Comment by IzzySoft** [comment]
Thanks for adding the name back! Guess all points are solved now, so this issue can be closed. Should there be questions from your side (eg. concerning my repo), I of course gladly answer them, too.
